### PR TITLE
[BREAKING CHANGE] Modify full shard key rlp in evm tx

### PR DESCRIPTION
**Pull request by ninjaahhh**
brought up by @pingke, seems it doesn't give much benefit using different serialization for shard key

note this is a breaking change. shouldn't merge in current network. should be for root chain.

### CODE REVIEW

**Comment by qizhou** [comment]
Current minimum size transaction should adopt most fields in 0 (note that the transactions should be valid).  This will help us identify the max block size of a shard.

**Comment by qcdll** [comment]
so it would be best to change the min size accordingly as `from_full_shard_key` can be 0

**Comment by qizhou** [comment]
> so it would be best to change the min size accordingly as `from_full_shard_key` can be 0

Yes, in theory, a valid transaction could.

**Comment by ninjaahhh** [comment]
close this since we want to avoid breaking changes. let's keep `BigEndianInt(4))`

**Comment by ninjaahhh** [comment]
close this since we want to avoid breaking changes. let's keep `BigEndianInt(4))`

> close this since we want to avoid breaking changes. let's keep `BigEndianInt(4))`

cc @pingke

**Pull request closed without merging**
