### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by TahiG**
removed typos

### CODE REVIEW

**Comment by ninjaahhh** [comment]
thanks for checking, but it's intended to install `librocksdb-dev` from package manager instead of building from source since the latter takes more time. 

the down side of not building from source is the lack of lz4 compression support but we think it's fine for now (which means in the following snippet try-block will fail and then fall back to snappy)

https://github.com/QuarkChain/pyquarkchain/blob/30da626ef6b50bd07b230aac05a3cef7fd7f23cf/quarkchain/db.py#L73-L79

**Comment by TahiG** [comment]
My bad, hope I didn't offend. Carry on! :)

**Comment by TahiG** [comment]
I've just run it with my 'corrections' and it **is** taking forever.

**Comment by ninjaahhh** [comment]
no problem :)
from our previous experiences building rocksdb from source roughly takes about 20 minutes

**Pull request closed without merging**
