### PR TITLE
add tracking of objects in memory

### PR DESCRIPTION
**Pull request by qcdll**
dead simple, let's see if this reveals something
I tried a few options to track pypy memory usage/leak, eg tracemalloc, vmprof
but in the end only objgraph seems to work OK:
https://stackoverflow.com/questions/45210681/how-do-i-profile-memory-usage-with-pypy

### CODE REVIEW

**Comment by qizhou** [comment]
Wohu!!!

**Comment by ninjaahhh** [comment]
oh, realized we probably don't need to merge this.

**Comment by qcdll** [comment]
well, this looks cheap so why not
===
ran this on some cluster for a few hours and master.py memory grew to 1+gb
output is https://gist.github.com/3bf8d3c73ea6e5b62af0c44239fa196a
weakref looks suspicious

**Comment by qcdll** [comment]
this did not uncover the real memory leak (weakref is red herring)

so not going to merge this

**Pull request closed without merging**
